[versions]
adyen_version = "4.7.1"
androidx_appcompat_version = "1.6.1"
androidx_browser_version = "1.5.0"
androidx_cardview_version = "1.0.0"
androidx_constraintlayout_version = "2.1.4"
androidx_compose = "1.5.0-rc01"
androidx_compose_material3 = "1.1.1"
androidx_compose_compiler = "1.5.2"
androidx_ktx_version = "1.6.0"
androidx_lifecycle_ktx_version = "2.4.1"
androidx_lifecycle_version = "2.2.0"
androidx_multidex_version = "2.0.1"
androidx_navigation_version = "2.6.0"
androidx_palette_version = "1.0.0"
androidx_preference_version = "1.2.1"
androidx_recyclerview_version = "1.3.1"
androidx_room_version = "2.5.2"
androidx_vector_drawable_version = "1.1.0"
androidx_viewpager_version = "1.0.0"
appcoins_sdk_dev_version = "0.6.7.0"
appcoins_sdk_version = "0.6.7.0"
appsflyer_version = "6.3.2"
aptoide_analytics_version = "1.0.3"
asf_applications_version = "6"
asf_sdk_version = "0.4.5.19b"
androidx_biometrics_version = "1.1.0"
bintray_plugin_version = "1.7.3"
build_tools_version = "30.0.3"
collapsingtoolbarlayout_version = "1.0.0"
coil_version = "2.3.0"
commons_lang3_version = "3.7"
corektx_version = "1.10.1"
coroutines_version = "1.7.1"
cpp_version = "2.5.4"
dagger_version = "2.27"
desugar_version = "2.0.3"
epoxy_version = "4.5.0"
erc681_version = "0.36"
ethereumj_sdk_version = "0.5.0.0"
espresso_version = "3.4.0"
firebase_bom = "32.2.3"
firebase_crashlytics_plugin = "2.9.9"
firebase_performance_plugin = "1.4.2"
flurry_version = "14.0.0"
flexbox_version = "3.0.0"
glide_version = "4.12.0"
google_services = "4.3.15"
gradle_bintray_version = "1.7.3"
gradle_version = "3.3.2"
gradle_plugin_version = "8.1.1"
gson_version = "2.9.0"
hilt_czerwinski_extensions_version = "1.3.0"
hilt_version = "2.47"
hilt_compose_navigation = "1.1.0-alpha01"
indicative_version = "1.1.0"
intercom_version = "12.5.3"
jackson_version = "2.10.3"
jetbrains_annotations_version = "23.0.0"
junit5_version = "5.8.2"
junit5_plugin_version = "1.8.2.1"
junit_version = "4.13.2"
kotlin_version = "1.9.0"
ksp_version = "1.9.0-1.0.11"
ktx_version = "1.3.0"
lottie_version = "6.0.0"
material_version = "1.9.0"
michel_bull_kotlin_result = "1.1.16"
mockito_version = "3.3.0"
okhttp_version = "4.10.0"
paranoid_version = "0.3.3"
play_services_vision_version = "20.1.3"
referrer_version = "2.2"
retrofit_version = "2.9.0"
rxandroid_version = "2.1.1"
rxbinding_version = "2.1.1"
rxjava_version = "2.2.19"
rxlifecycle_version = "1.0"
androidx_securitycrypto_version = "1.1.0-alpha06"
sentry_version = "1.7.30"
shimmer_version = "0.5.0"
spongycastle_version = "1.58.0.0" #it was "1.58.0.0@jar"?
support_annotations = "28.0.0"
test_ext_version = "1.1.5"
turbine_version = "0.12.1"
viewBindingDelegate = "1.5.9"
web3j_version = "4.8.8-android"
androidx_work_version = "2.8.1"
zxing_android_version = "3.6.0"
zxing_version = "3.4.0"
jacoco_version = "0.8.8"
mockk_version = "1.13.3"
paging_version = "3.2.0"
paging_compose_version = "3.2.0"

[libraries]
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx_navigation_version" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx_navigation_version" }
androidx-navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx_navigation_version" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx_ktx_version" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx_ktx_version" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx_ktx_version" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx_version" }

androidx-appcompact = { module = "androidx.appcompat:appcompat", version.ref = "androidx_appcompat_version" }
androidx-vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "androidx_vector_drawable_version" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx_recyclerview_version" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx_cardview_version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraintlayout_version" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx_preference_version" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx_palette_version" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx_multidex_version" }
androidx-viewpager = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx_viewpager_version" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx_browser_version" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidx_biometrics_version" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx_room_version" }
androidx-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "androidx_room_version" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx_room_version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx_room_version" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx_work_version" }
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "androidx_work_version" }

#androidx-compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx_lifecycle_ktx_version" }
#androidx-compose-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx_lifecycle_ktx_version" }
androidx-compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_compose_navigation" }

androidx-lifecycle-ktx-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx_lifecycle_ktx_version" }
androidx-lifecycle-ktx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle_ktx_version" }
androidx-lifecycle-ktx-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx_lifecycle_ktx_version" }
androidx-lifecycle-ktx-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx_lifecycle_ktx_version" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx_lifecycle_version" }

compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx_compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx_compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx_compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx_compose_material3" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx_compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx_compose" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx_compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx_compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx_compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "androidx_compose" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil_version" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx_compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx_compose_compiler" }
compose-lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie_version" }

network-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit_version" }
network-retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit_version" }
network-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit_version" }
network-retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit_version" }
network-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp_version" }

google-gson = { module = "com.google.code.gson:gson", version.ref = "gson_version" }
google-material = { module = "com.google.android.material:material", version.ref = "material_version" }
google-services = { module = "com.google.gms:google-services", version.ref = "google_services" }
google-play-services = { module = "com.google.android.gms:play-services-vision", version.ref = "play_services_vision_version" }
google-zxing = { module = "com.google.zxing:core", version.ref = "zxing_version" }
zxing-android = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing_android_version" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase_bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt_version" }
# hilt-interface-extensions to allow injecting an implementation that has an interface
hilt-interface-extensions = { module = "it.czerwinski.android.hilt:hilt-extensions", version.ref = "hilt_czerwinski_extensions_version" }
hilt-interface-extensions-processor = { module = "it.czerwinski.android.hilt:hilt-processor", version.ref = "hilt_czerwinski_extensions_version" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_version" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines_version" }
kotlin-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines_version" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "michel_bull_kotlin_result" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "michel_bull_kotlin_result" }

rx-rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava_version" }
rx-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid_version" }
rx-rxbinding = { module = "com.jakewharton.rxbinding2:rxbinding", version.ref = "rxbinding_version" }
rx-rxlifecyle = { module = "com.trello:rxlifecycle", version.ref = "rxlifecycle_version" }
rx-rxlifecyle-components = { module = "com.trello:rxlifecycle-components", version.ref = "rxlifecycle_version" }

adyen-card = { module = "com.adyen.checkout:card", version.ref = "adyen_version" }
adyen-redirect = { module = "com.adyen.checkout:redirect", version.ref = "adyen_version" }
adyen-3ds2 = { module = "com.adyen.checkout:3ds2", version.ref = "adyen_version" }

appcoins-sdk = { module = "io.catappult:appcoins-contract-proxy", version.ref = "appcoins_sdk_version" }
appcoins-sdk-debug = { module = "io.catappult:appcoins-contract-proxy", version.ref = "appcoins_sdk_dev_version" }
appcoins-sdk-communication = { module = "io.catappult:communication", version.ref = "appcoins_sdk_version" }

analytics-sentry = { module = "io.sentry:sentry-android", version.ref = "sentry_version" }
analytics-indicative = { module = "com.indicative.client.android:Indicative-Android", version.ref = "indicative_version" }
analytics-flurry = { module = "com.flurry.android:analytics", version.ref = "flurry_version" }
analytics-appsflyer = { module = "com.appsflyer:af-android-sdk", version.ref = "appsflyer_version" }

viewbinding-delegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version.ref = "viewBindingDelegate" }
intercom = { module = "io.intercom.android:intercom-sdk", version.ref = "intercom_version" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide_version" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide_version" }
coil-kt = { module = "io.coil-kt:coil", version.ref = "coil_version" }
coil-kt-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil_version" }
coil-kt-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil_version" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie_version" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer_version" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxy_version" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy_version" }
cpp = { module = "com.hbb20:ccp", version.ref = "cpp_version" }
android-installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "referrer_version" }
android-support-annotations = { module = "com.android.support:support-annotations", version.ref = "support_annotations" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons_lang3_version" }
paranoid = { module = "io.michaelrocks:paranoid-core", version.ref = "paranoid_version" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox_version" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations_version" }
jackson-annotation = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson_version" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson_version" }
spongycastle-core = { module = "com.madgag.spongycastle:core", version.ref = "spongycastle_version" }
spongycastle-prov = { module = "com.madgag.spongycastle:prov", version.ref = "spongycastle_version" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_version" }
paging = { module = "androidx.paging:paging-runtime", version.ref = "paging_version" }
paging_compose = { module = "androidx.paging:paging-compose", version.ref = "paging_compose_version" }

web3j = { module = "org.web3j:core", version.ref = "web3j_version" }
kethereum-erc681 = { module = "com.github.walleth.kethereum:erc681", version.ref = "erc681_version" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx_securitycrypto_version" }

test-mockito = { module = "org.mockito:mockito-core", version.ref = "mockito_version" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk_version" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_version" }
test-junit = { module = "junit:junit", version.ref = "junit_version" }
test-junit-ext = { module = "androidx.test.ext:junit", version.ref = "test_ext_version" }
test-junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5_version" }
test-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5_version" }
test-junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5_version" }
test-junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5_version" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine_version" }

# Dependencies of the included build-logic
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "gradle_plugin_version" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
gradlePlugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version" }
gradlePlugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt_version" }
gradlePlugin-junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "junit5_plugin_version" }
gradlePlugin-bintray = { module = "com.jfrog.bintray.gradle:gradle-bintray-plugin", version.ref = "bintray_plugin_version" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase_crashlytics_plugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebase_performance_plugin" }

[bundles]
androidx-room = ["androidx-room-runtime", "androidx-room-rxjava2", "androidx-room-ktx"]
androidx-lifecycle = ["androidx-lifecycle-ktx-runtime", "androidx-lifecycle-ktx-viewmodel", "androidx-lifecycle-ktx-viewmodel-savedstate", "androidx-lifecycle-ktx-common-java8", "androidx-lifecycle-extensions"]
androidx-work = ["androidx-work-runtime", "androidx-work-rxjava2"]
androidx-compose = ["compose-ui-viewbinding", "compose-ui-util", "compose-ui-ui", "compose-ui-preview", "compose-ui-tooling", "compose-ui-test", "compose-material3", "compose-foundation-layout", "compose-foundation-foundation", "compose-animation-animation", "compose-compiler", "compose-activity"]
coil = ["coil-kt", "coil-kt-compose", "coil-kt-svg"]
network = ["network-retrofit", "network-retrofit-adapter-rxjava", "network-retrofit-converter-gson", "network-retrofit-converter-jackson", "network-okhttp", "google-gson"]
adyen = ["adyen-card", "adyen-redirect", "adyen-3ds2"]
analytics = ["analytics-sentry", "analytics-indicative", "analytics-flurry", "analytics-appsflyer"]
testing = ["test-junit", "test-mockito", "test-espresso", "test-mockk"]
jackson = ["jackson-annotation", "jackson-databind"]
hilt-implementation = ["hilt-android", "hilt-interface-extensions", "androidx-compose-hilt-navigation"]
hilt-kapt = ["hilt-compiler", "hilt-interface-extensions-processor"]
rx = ["rx-rxjava", "rx-rxandroid", "rx-rxbinding"]
result = ["kotlin-result-coroutines", "kotlin-result"]
paging = ["paging", "paging_compose"]

[plugins]
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase_performance_plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase_crashlytics_plugin" }
android-application = { id = "com.android.application", version.ref = "gradle_plugin_version" }
android-library = { id = "com.android.library", version.ref = "gradle_plugin_version" }
android-test = { id = "com.android.test", version.ref = "gradle_plugin_version" }